version: "3.8"
services:
  mysql:
    container_name: "mwa_mysql"
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
  redis:
    container_name: "mwa_redis"
    image: "redis"
  elasticsearch:
    container_name: "mwa_elasticsearch"
    image: "elasticsearch:7.11.1"
    environment:
      discovery.type: "single-node"
  kibana:
    container_name: "mwa_kibana"
    image: "kibana:7.11.1"
    depends_on:
      - "elasticsearch"
    links:
      - "elasticsearch"
  service:
    container_name: "mwa_service"
    image: "node"
    working_dir: /app
    links:
      - mysql
      - redis
      - elasticsearch
    depends_on:
      - mysql
      - redis
      - elasticsearch
    volumes:
      - ./:/app
    command: "tail -f /dev/null"